version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - RUBY_ENV=development
        - REDMINE_LANG=en
    # ports:
    #   - 3000:3000
    # command: [rails, s]
    command: [sleep, infinity]
    volumes:
      - ./:/app/
    networks:
      - redmine
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: redmine
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - redmine

volumes:
  pgdata:

networks:
  redmine:
